name: On-demand self-hosted runner for GitHub Actions
description: GitHub Action for automatic AWS EC2 instance provisioning as a GitHub Actions self-hosted runner.
author: zama-ai
branding:
  icon: 'box'
  color: 'orange'
inputs:
  mode:
    description: >-
      Specify here which mode you want to use:
        - 'start' - to start a new runner;
        - 'stop' - to stop the previously created runner.
    required: true
  github-token:
    description: >-
      GitHub Personal Access Token with the 'repo' scope assigned.
    required: true
  slab-url:
    description: >-
      URL to Slab CI server.
    required: true
  job-secret:
    description: >-
      Secret key used by Slab to perform HMAC computation.
    required: true
  backend:
    description: >-
      Backend provider name to look for in slab.toml file in repository that uses the action.
      This input is required if you use the 'start' mode.
    required: false
  profile:
    description: >-
      Profile to use as described slab.toml file in repository that uses the action.
      This input is required if you use the 'start' mode.
    required: false
  runner-id:
    description: >-
      Unique ID assigned to the runner.
      The runner ID is used to remove the runner from GitHub when the runner is not needed anymore.
      This input is required if you use the 'stop' mode.
    required: false

outputs:
  label:
    description: >-
      Name of the unique label assigned to the runner.
      Use `label` as the input of `runs-on` workflow property to run subsequent jobs.
  id:
    description: >-
      Unique ID assigned to the runner.
      Use `id` as input of `runner-id` action property remove the runner from GitHub when it is not needed anymore.
runs:
  using: node20
  main: ./dist/index.js
