# Test action to check support of various Terraform providers
name: Test Terraform Providers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-terraform-scaleway:
    name: test-terraform-scaleway
    uses: ./.github/workflows/test_spawn_terminate_common.yml
    with:
      backend: terraform
      profile: scaleway-ci-test
    secrets:
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_URL }}
      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}


