# Test action to spawn/terminate backend instance
name: Test Spawn-Terminate

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  aws-provider:
    name: test_spawn_terminate/aws-provider (bpr)
    uses: ./.github/workflows/spawn_terminate_common.yml
    with:
      backend: aws
      profile: ci-test
    secrets:
      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_BASE_URL_PRE_PROD }}

  hyperstack-provider:
    name: test_spawn_terminate/hyperstack-provider (bpr)
    uses: ./.github/workflows/spawn_terminate_common.yml
    with:
      backend: hyperstack
      profile: ci-test
    secrets:
      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_BASE_URL_PRE_PROD }}
