# Test action to check support of various Terraform providers
name: Test Terraform Providers

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  terraform-aws:
    name: test_terraform_providers/terraform-aws (bpr)
    uses: ./.github/workflows/spawn_terminate_common.yml
    with:
      backend: terraform
      profile: aws-ci-test
    secrets:
      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_BASE_URL_PRE_PROD }}

  terraform-scaleway:
    name: test_terraform_providers/terraform-scaleway (bpr)
    uses: ./.github/workflows/spawn_terminate_common.yml
    with:
      backend: terraform
      profile: scaleway-ci-test
    secrets:
      REPO_CHECKOUT_TOKEN: ${{ secrets.REPO_CHECKOUT_TOKEN }}
      JOB_SECRET: ${{ secrets.JOB_SECRET }}
      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
      SLAB_URL: ${{ secrets.SLAB_BASE_URL_PRE_PROD }}
